### ISSUE TITLE
Potential double-counting of emission probs for first obs per patient

### ISSUE THREAD

**Issue by prockenschaub** [mb2019/Comorbidity-HMM#1]
Thanks for the manuscript and the nicely documented code here, it's been a very interesting and helpful read!

While going through the code in `CHMM_comorbidity.stan`, I stumbled over something that I couldn't quite understand and which might be an unintended minor bug. Starting in line 121, the emission lpdf for each patient's following observations is calculated:

https://github.com/mb2019/Comorbidity-HMM/blob/d3ae48525bc8aab764162fc347c89850d5f47f82/Models/CHMM_comorbidity.stan#L117

### Potential Issue

I believe that the lines 121-126 should be in an `else` statement. The way it is currently written, the emission lpdf of the first observed omission is counted twice. 

### Alternative 

Wrapping this block in an `else` statement models the starting probability in each patient's first time step as a long-term constant, without regard for patient covariates in `Covar`. Conceptually, I suppose one could also think of `pi_initial` as the probability at `t=0` and also have the starting probability modelled in `log_gamma_tr`. In this case, the `else` could be omitted but I believe then the `normal_lpdf` commands in lines 117 and 118 would need to be removed to avoid double-counting the first emission. 

In any case, this is in all likelihood a minor issue that won't impact fitted estimates much. I just thought I flag it since it's an easy fix (if it indeed is a bug and I haven't missed anything).

**Comment by mb2019** [comment]
Please excuse the very late reply. This is indeed an unintended minor bug. I have now adjusted the code by including an `else` statement as well as changing `log_gamma_tr[t,k]` to `log_gamma_tr[t-1,k]`, which is similar to your suggested alternative.
